import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HistoryView from "./components/historyView";
import TopBar from "./components/topBar";
import ConfigArea from "./components/configArea";
import CpsController from "./components/Controller";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
        <CpsController>
          
          <TopBar />

          <div className="flex p-2">

            <div className="w-1/6">
              <HistoryView />
            </div>
            
            <main className="flex-1 p-6">
              {children}
            </main>

            <div className="w-1/6">
              <ConfigArea />
            </div>

          </div>

        </ CpsController>

      </body>
    </html>
  );
}
